coursovaya/urls.py
from django.contrib import admin
from django.urls import include, path
from forms.urls import router

urlpatterns = [
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
]

forms/urls.py
from rest_framework.routers import DefaultRouter
from forms.views import CategoryView, FormView, PassedView, UserView, AnswerView


router = DefaultRouter()

router.register('category', CategoryView, basename='category')
router.register('form', FormView, basename='form')
router.register('passed-form', PassedView, basename='passed-form')
router.register('user', UserView, basename='user')
router.register('answer', AnswerView, basename='answer')

forms/models.py
from tabnanny import verbose
from django.db import models
from django.utils import timezone

class Question(models.Model):
    text = models.CharField(max_length=1024, verbose_name="Текст")

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = "Вопрос"
        verbose_name_plural = "Вопросы"

class Form(models.Model):
    name = models.CharField(max_length=255, verbose_name="Имя")
    pub_date = models.DateTimeField('date published')
    questions = models.ManyToManyField(Question)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Анкета"
        verbose_name_plural = "Анкеты"
        
class User(models.Model):
    name = models.CharField(max_length=100, default="noname", verbose_name="Имя")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

class Passed_Form(models.Model):
    form = models.ForeignKey(Form, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.form.name

    class Meta:
        verbose_name = "Пройденная форма"
        verbose_name_plural = "Пройденные формы"

class Answer(models.Model):
    passed_form = models.ForeignKey(Passed_Form, related_name="answer", on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=255, verbose_name="Текст")

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = "Ответ"
        verbose_name_plural = "Ответы"

class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name="Имя")
    forms = models.ManyToManyField(Form)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
    

forms/admin.py
import site
from django.contrib import admin

from .models import Category, Form, Question, Passed_Form, Answer, User

class CategoryAdmin(admin.ModelAdmin):
    list_display = ('name', 'get_forms')

    def get_forms(self, obj):
        return [f.name for f in obj.forms.all()]

    get_forms.short_description = 'Формы'

class FormAdmin(admin.ModelAdmin):
    list_display = ('name', 'get_questions')

    def get_questions(self, obj):
        return [q.text for q in obj.questions.all()]
    
    get_questions.short_description = 'Вопросы'

class QuestionAdmin(admin.ModelAdmin):
    list_display = ('text',)

class AnswerAdmin(admin.ModelAdmin):
    list_display = ('text',)

class UserAdmin(admin.ModelAdmin):
    list_display = ('name',)

class Passed_FormAdmin(admin.ModelAdmin):
    list_display = ('get_name',)

    def get_name(self, obj):
        return obj.form.name

    get_name.short_description = 'Вопросы'


admin.site.register(Category, CategoryAdmin)
admin.site.register(Question, QuestionAdmin)
admin.site.register(Passed_Form, Passed_FormAdmin)
admin.site.register(Answer, AnswerAdmin)
admin.site.register(Form, FormAdmin)
admin.site.register(User, UserAdmin)

forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'forms'

forms/serializers.py
from rest_framework import serializers
from forms.models import Category, Form, Passed_Form, User, Answer

class CategorySerializer(serializers.ModelSerializer):
  class Meta:
    model = Category
    fields = ['name', 'forms']

class UserSerializer(serializers.ModelSerializer):
  class Meta:
    model = User
    fields = ['name']

class FormSerializer(serializers.ModelSerializer):
  class Meta:
    model = Form
    fields = ['name', 'pub_date', 'questions']

class AnswerSerializer(serializers.ModelSerializer):
  passed_form = serializers.PrimaryKeyRelatedField(many=False, read_only=True)
  question = serializers.PrimaryKeyRelatedField(many=False, read_only=True)

  class Meta:
    model = Answer
    fields = ['passed_form', 'question', 'text']

class PassedSerializer(serializers.ModelSerializer):
  form = FormSerializer(many=False, read_only=True)
  user = UserSerializer(many=False, read_only=True)
  answer = AnswerSerializer(many=True, read_only=True)

  class Meta:
    model = Passed_Form
    fields = ['form', 'user', 'answer']

forms/tests.py
from django.test import TestCase

# Create your tests here.

forms/views.py
from rest_framework.viewsets import ModelViewSet
from rest_framework.pagination import PageNumberPagination
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.exceptions import ValidationError, NotFound
from rest_framework.filters import SearchFilter
from forms.serializers import CategorySerializer, FormSerializer, PassedSerializer, UserSerializer, AnswerSerializer
from django.db.models import Q
from django.views import generic
from django.shortcuts import get_object_or_404
from django_filters.rest_framework import DjangoFilterBackend

from forms.models import Category, Form, Answer, Passed_Form, User, Question

class IndexView(generic.ListView):
    template_name = 'forms/index.html'
    model = Category
    context_object_name = 'category_list'

class CategoryView(ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

class FormsViewPagination(PageNumberPagination):
    page_size = 10
    page_query_param = 'page_size'
    max_page_size = 10
class FormView(ModelViewSet):
    queryset = Form.objects.all()
    serializer_class = FormSerializer
    pagination_class = FormsViewPagination

    @action(methods=['GET'], detail=True)
    def form_search(self, _, **kwargs):
        value = kwargs.get('pk')
        
        if not value:
            raise NotFound({'error': 'no value no gain'})

        got_forms = Passed_Form.objects.filter(Q(form=value))

        serializer = PassedSerializer(data=got_forms, many=True)
        serializer.is_valid()
        return Response(serializer.data)

    @action(methods=['GET'], detail=False)
    def last_forms(self, _):
        last_forms = Form.objects.all().order_by('-pub_date')
        page = self.paginate_queryset(last_forms)

        if page is not None:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)

        serializer = FormSerializer(data=last_forms, many=True)
        serializer.is_valid()
        return Response(serializer.data)
class PassedView(ModelViewSet):
    queryset = Passed_Form.objects.all()
    serializer_class = PassedSerializer

    @action(methods=['POST'], detail=False)
    def add_passed_form(self, request):
        try:
            curForm = get_object_or_404(Form, pk=request.data.get('id'))
        except:
            raise NotFound({'error': 'form not found' + str(request.data.get('id'))})

        if request.data.get('user') and request.data.get('user') != '':
            try:
                username = User.objects.get(name=request.data.get('user'))
            except:
                username = User(name=request.data.get('user'))
                username.save()
        else: 
            raise ValidationError({'error': 'username must not be empty'})

        new_passed_form = Passed_Form(form = curForm, user = username)
        new_passed_form.save()
        for answer in request.data.get('answers'):
            if answer.get('text') and answer.get('text') != '':
                new_answer = Answer(passed_form = new_passed_form, question = get_object_or_404(Question, pk=answer.get('question_id')), text = answer.get('text'))
                new_answer.save()
            else:
                raise ValidationError({'error': 'all questions should be answered'})
        
        return Response({"message": "form successfully added"})
class AnswerView(ModelViewSet):
    queryset = Answer.objects.all()
    serializer_class = AnswerSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['text']
class UserView(ModelViewSet):
    queryset = User.objects.all().order_by('-name')
    serializer_class = UserSerializer

    filter_backends = [SearchFilter]
    search_fields = ['id']

forms/templates/forms/category.html
<!DOCTYPE html>
<html lang="ru">  
    <head>
        <title>{{ category.name }}</title>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'forms/style.css' %}">
    </head> 
    <body>
        {% include "forms/header.html" %}
        <main class="main">
            <h1>{{ category.name }}</h1>
            {% if category.forms.all %}
                <ul class="main__list list">
                {% for form in category.forms.all %}
                    <li class="list__elem"><a href="{% url 'forms:form' form.id %}">{{ form.name }}</a></li>
                {% endfor %}
                </ul>
            {% else %}
                <span>Пока нет опросов в этой категории :(</span>
            {% endif %}
        </main>
    </body>
</html>

forms/templates/forms/form.html
<!DOCTYPE html>
<html lang="ru">  
    <head>
        <title>Анкета</title>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'forms/style.css' %}">
    </head>
    </body>
        {% include "forms/header.html" %}
        <main class="main">
            <h1>{{ form.name }}</h1>
            <form action="{% url 'forms:submit' form.id %}" method="post" class="main__form form">
            {% csrf_token %}
                <div class="form__question">
                    <label for="name">Ваше имя</label>
                    <input type="text" required id="name" name="name">
                </div>
                {% for question in form.questions.all %}
                    <div class="form__question">
                        <label for="question{{ forloop.counter }}">{{ question.text }}</label>
                        <input type="text" required id="question{{ forloop.counter }}"  name="{{ question.id }}">
                    </div>
                {% endfor %}
                <input type="submit" value="Отправить">
            </form>
        </main>
    </body>
</html>

forms/templates/forms/header.html
<header class="header">
    <nav class="header__nav nav">
        <a href="{% url 'forms:index' %}" class="nav__elem">На главную</a>
        <a href="{% url 'forms:passed' %}" class="nav__elem">Пользователи</a>
    </nav>
</header>

forms/templates/forms/index.html
<!DOCTYPE html>
<html lang="ru">  
    <head>
        <title>Категории</title>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'forms/style.css' %}">
    </head>
    <body>
        {% include "forms/header.html" %} 
        <main class="main">
            <h1>Выберите категорию</h1>
            {% if category_list %}
                <ul class="main__list list">
                    {% for category in category_list %}
                        <li class="list__elem"><a href="{% url 'forms:category' category.id %}">{{ category.name }}</a></li>
                    {% endfor %} 
                </ul>
            {% else %}
                <span>Сейчас категорий нет</span>
            {% endif %}
        </main>
    </body>
</html>

forms/templates/forms/passed.html
<!DOCTYPE html>
<html lang="ru">  
    <head>
        <title>Пользователи</title>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'forms/style.css' %}">
    </head>
    <body>    
        {% include "forms/header.html" %}
        <main class="main">
            <h1>Пользователи</h1>
            {% if user_list %}
                <ul class="main__list list">
                    {% for user in user_list %}
                        <li class="list__elem"><a href="{% url 'forms:user' user.id %}">{{ user.name }}</a></li>
                    {% endfor %} 
                </ul>
            {% else %}
                <span>Пройденных анкет еще нет</span>
            {% endif %}
        </main>
    </body>
</html>

forms/templates/forms/passed_form.html
<!DOCTYPE html>
<html lang="ru">  
    <head>
        <title>Ответы на анкету</title>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'forms/style.css' %}">
    </head>
    <body>
        {% include "forms/header.html" %}
        <main class="main">
            <h1>
                {{ passed_form.form.name }}
            </h1>
            {% if passed_form.answer_set.all %}
                <ul class="main__list list">
                {% for answer in passed_form.answer_set.all %}
                    <li class="list__elem answer">
                        <div class="answer__block">
                            <span class="block__question-text">{{ answer.question.text }}</span>
                            <span class="block__answer-text">{{ answer.text }}<span>
                        </div>
                    </li>
                {% endfor %}
                </ul>
            {% else %}
                <span>Ответов не будет :(</span>
            {% endif %}
        </main>
    </body>
</html>

forms/templates/forms/user.html
<!DOCTYPE html>
<html lang="ru">  
    <head>
        <title>{{ user.name }}</title>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'forms/style.css' %}">
    </head> 
    <body>
        {% include "forms/header.html" %}
        <main class="main">
            <h1>{{ user.name }}</h1>
            {% if user.passed_form_set.all %}
                <ul class="main__list list">
                {% for passed_form in user.passed_form_set.all %}
                    <li class="list__elem"><a href="{% url 'forms:passed_form' passed_form.id %}">{{ passed_form.form.name }}</a></li>
                {% endfor %}
                </ul>
            {% else %}
                <span>У пользователя пока нет пройденных анкет :(</span>
            {% endif %}
        </main>
    </body>
</html>